defaults: &defaults
  welcome_text: <%= ENV['VULCAN_WELCOME_TEXT'] || nil %>
  contact_email: <%= ENV['VULCAN_CONTACT_EMAIL']%>
  smtp:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_SMTP']) %>
    settings:
      address: <%= ENV['VULCAN_SMTP_ADDRESS'] %>
      port: <%= ENV['VULCAN_SMTP_PORT'] %>
      domain: <%= ENV['VULCAN_SMTP_DOMAIN'] %>
      authentication: <%= ENV['VULCAN_SMTP_AUTHENTICATION']&.to_sym %>
      tls: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_SMTP_TLS']) %>
      openssl_verify_mode: <%= ENV['VULCAN_SMTP_OPENSSL_VERIFY_MODE'] %>
      enable_starttls_auto: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_SMTP_ENABLE_STARTTLS_AUTO']) %>
      user_name: <%= ENV['VULCAN_SMTP_SERVER_USERNAME'] %>
      password: <%= ENV['VULCAN_SMTP_SERVER_PASSWORD'] %>
  local_login:
    enabled: <%= ENV['VULCAN_ENABLE_LOCAL_LOGIN'] || true %>
    email_confirmation: <%= ENV['VULCAN_ENABLE_EMAIL_CONFIRMATION'] || false %>
    session_timeout: <%= ENV['VULCAN_SESSION_TIMEOUT'] || 60 %>
  ldap:
    enabled: <%= ENV['VULCAN_ENABLE_LDAP'] || true %>
    servers:
      main:
        host: <%= ENV['VULCAN_LDAP_HOST'] || 'localhost' %>
        port: <%= ENV['VULCAN_LDAP_PORT'] || 389 %>
        title: <%= ENV['VULCAN_LDAP_TITLE'] || 'LDAP' %>
        uid: <%= ENV['VULCAN_LDAP_ATTRIBUTE'] || 'uid' %>
        encryption: <%= ENV['VULCAN_LDAP_ENCRYPTION'] || 'plain' %>
        bind_dn: <%= ENV['VULCAN_LDAP_BIND_DN'] %>
        password: <%= ENV['VULCAN_LDAP_ADMIN_PASS'] %>
        base: <%= ENV['VULCAN_LDAP_BASE'] %>
        disable_verify_certificates: <%= ENV['VULCAN_LDAP_CERT_VERIFY'] || false %>
  providers:

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
