# Overcommit configuration for Rails projects
# https://github.com/sds/overcommit

# Use bundled version of overcommit
gemfile: Gemfile

# Hooks that run during `git commit`
CommitMsg:
  # Enforce proper commit message format
  CapitalizedSubject:
    enabled: true
    description: 'Check subject capitalization'
  EmptyMessage:
    enabled: true
    description: 'Check for empty commit message'
  TextWidth:
    enabled: true
    description: 'Check text width'
    max_subject_width: 72
    max_body_width: 80
  TrailingPeriod:
    enabled: true
    description: 'Check for trailing periods in subject'
  SingleLineSubject:
    enabled: true
    description: 'Check subject is single line'

# Hooks that run before `git commit`
PreCommit:
  # Ruby/Rails specific hooks
  RuboCop:
    enabled: true
    description: 'Analyze Ruby code with RuboCop'
    required_executable: 'bundle'
    command: ['bundle', 'exec', 'rubocop']
    flags: ['--autocorrect-all', '--display-cop-names']
    on_warn: fail # Treat warnings as failures
    problem_on_unmodified_line: report
    include:
      - '**/*.rb'
      - '**/*.rake'
      - '**/Gemfile'
      - '**/Rakefile'
    exclude:
      - 'db/schema.rb'  # Auto-generated by Rails migrations
      - 'db/structure.sql'  # Auto-generated by Rails

  RailsBestPractices:
    enabled: false # Enable when ready
    description: 'Analyze with rails_best_practices'
    required_executable: 'bundle'
    command: ['bundle', 'exec', 'rails_best_practices']

  RailsSchemaUpToDate:
    enabled: true
    description: 'Check if db/schema.rb matches migrations'

  BundleCheck:
    enabled: true
    description: 'Check Gemfile dependencies'

  # JavaScript/Vue specific hooks
  EsLint:
    enabled: true
    description: 'Analyze JavaScript/Vue with ESLint'
    required_executable: 'yarn'
    command: ['yarn', 'lint']
    include:
      - '**/*.js'
      - '**/*.vue'

  # Shell script hooks
  ShellCheck:
    enabled: false
    description: 'Analyze shell scripts with ShellCheck'
    include:
      - '**/*.sh'
      - '**/bin/*'
    exclude:
      - '**/bin/*.rb'
      - '**/bin/bundle'
      - '**/bin/rails'
      - '**/bin/rake'
      - '**/bin/webpack'
      - '**/bin/webpack-dev-server'
      - '**/bin/yarn'

  # General hooks
  TrailingWhitespace:
    enabled: false  # Using FixTrailingWhitespace instead

  FixTrailingWhitespace:
    enabled: true
    exclude:
      - '**/db/schema.rb'
      - '**/db/structure.sql'
      - '**/*.md'

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true
    include:
      - '**/*.yml'
      - '**/*.yaml'

  JsonSyntax:
    enabled: true
    include:
      - '**/*.json'

  HardTabs:
    enabled: true
    exclude:
      - '**/Makefile'
      - '**/*.mk'

  # Security scanning (disabled by default for speed)
  Brakeman:
    enabled: false
    description: 'Security scan with Brakeman'
    command: ['bundle', 'exec', 'brakeman', '--quiet', '--summary']

  BundleAudit:
    enabled: false
    description: 'Check for vulnerable gem versions'

# Hooks that run after `git checkout`
PostCheckout:
  BundleInstall:
    enabled: true
    description: 'Install bundle dependencies'

  YarnInstall:
    enabled: true
    description: 'Install yarn dependencies'

  ActiveRecordMigrations:
    enabled: true
    description: 'Run pending migrations'

# Hooks that run after `git merge`
PostMerge:
  BundleInstall:
    enabled: true

  YarnInstall:
    enabled: true

  ActiveRecordMigrations:
    enabled: true

# Hooks that run after `git rewrite`
PostRewrite:
  BundleInstall:
    enabled: true

  YarnInstall:
    enabled: true