require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    # - config/initializers/*
    - node_modules/**/*
    - "vendor/**/*"
Layout/LineLength:
  Max: 120
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 120
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 750
Metrics/ModuleLength:
  Max: 750
  Exclude:
    - "app/controllers/concerns/*_cache_helper.rb"
Metrics/ParameterLists:
  Max: 8
Metrics/BlockLength:
  Enabled: false
  Exclude:
    - spec/**/*
Rails/ContentTag:
  Enabled: true
  Exclude:
    - "app/lib/**/*"
Rails/FilePath:
  EnforcedStyle: "arguments"
Rails/HasAndBelongsToMany:
  Enabled: false
Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*

# RSpec configuration - more lenient for existing codebase
RSpec/ExampleLength:
  Max: 120
  Exclude:
    - spec/**/*_integration_spec.rb
    - spec/**/*_critical_*_spec.rb
RSpec/MultipleExpectations:
  Max: 15
RSpec/MessageSpies:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
Style/OpenStructUse:
  Exclude:
    - spec/**/*
Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*
