plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    # - config/initializers/*
    - node_modules/**/*
    - "vendor/**/*"
Layout/LineLength:
  Max: 120
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Max: 120
  Exclude:
    - spec/**/*
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Max: 750
Metrics/ParameterLists:
  Max: 8
Metrics/BlockLength:
  Enabled: false
  Exclude:
    - spec/**/*
Rails/ContentTag:
  Enabled: true
  Exclude:
    - "app/lib/**/*"
Rails/FilePath:
  EnforcedStyle: "arguments"
Rails/HasAndBelongsToMany:
  Enabled: false
Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*

# RSpec configuration - more lenient for existing codebase
RSpec/ExampleLength:
  Max: 120
  Exclude:
    - spec/**/*_integration_spec.rb
    - spec/**/*_critical_*_spec.rb
RSpec/MultipleExpectations:
  Max: 15
RSpec/MessageSpies:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/SpecFilePathSuffix:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/AnyInstance:
  Enabled: false
RSpec/StubbedMock:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
Style/OpenStructUse:
  Exclude:
    - spec/**/*
Rails/SkipsModelValidations:
  Exclude:
    - spec/**/*

# ============================================================================
# PRE-EXISTING OFFENSES FROM RUBOCOP 1.25.1 → 1.79.2 UPGRADE
# These issues existed in master before the Ruby 3.1 upgrade (January 2025)
# See RUBOCOP-TECH-DEBT.md for tracking and fix strategies
# ============================================================================

# Hardcoded strings that should be in locale files (8 occurrences)
Rails/I18nLocaleTexts:
  Exclude:
    - app/controllers/stigs_controller.rb
    - app/models/additional_answer.rb
    - app/models/component_metadata.rb
    - app/models/membership.rb
    - app/models/project_access_request.rb
    - app/models/project_metadata.rb
    - app/models/security_requirements_guide.rb
    - app/models/stig.rb

# Large data collection hardcoded in source (1 occurrence)
Metrics/CollectionLiteralLength:
  Exclude:
    - app/lib/cci_map/constants.rb

# Methods that should end with ? (4 occurrences)
Naming/PredicateMethod:
  Exclude:
    - app/lib/xccdf/ident.rb
    - app/models/component.rb
    - app/models/concerns/prefix_validator.rb
    - app/controllers/concerns/oidc_discovery_helper.rb

# Safe navigation chains longer than 2 calls (5 occurrences)
Style/SafeNavigationChainLength:
  Exclude:
    - app/models/base_rule.rb
    - app/models/check.rb
    - app/models/component.rb
    - lib/tasks/stig_and_srg_puller.rake

# Missing class documentation comments (9 occurrences)
Style/Documentation:
  Exclude:
    - db/migrate/*
    - spec/**/*
    - app/lib/xccdf/idref/overrideable_idref.rb
    - app/lib/xccdf/item/selectable_item.rb
    - app/lib/xccdf/item/selectable_item/group.rb
    - app/lib/xccdf/item/selectable_item/rule.rb
    - app/lib/xccdf/item/value.rb
    - app/lib/xccdf/warning.rb
    - app/models/component_metadata.rb
    - app/models/project_access_request.rb
    - app/models/project_metadata.rb

# Test let statements with numbers in names (6 occurrences)
RSpec/IndexedLet:
  Exclude:
    - spec/controllers/registrations_controller_spec.rb
    - spec/models/project_access_request_spec.rb
