version: '3.8'

services:
  # PostgreSQL for testing
  db-test:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: vulcan_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - vulcan_test_db:/var/lib/postgresql/data

  # LDAP testing service 
  # Uses GitHub Action approach with support for multi-architecture
  ldap-test:
    image: bitnami/openldap:2.6
    # Automatically adapts to the host platform (ARM/x86)
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=GoodNewsEveryone
      - LDAP_ROOT=dc=planetexpress,dc=com
      - LDAP_PORT_NUMBER=389
      # Add zoidberg@planetexpress.com user to match tests
      - LDAP_USERS=zoidberg
      - LDAP_PASSWORDS=zoidberg
      - LDAP_USER_DC=people
      - LDAP_EMAILS=zoidberg@planetexpress.com
      - LDAP_ENABLE_TLS=no
    ports:
      - "389:389"
    # Add healthcheck to ensure LDAP is ready before tests run
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-D", "cn=admin,dc=planetexpress,dc=com", "-w", "GoodNewsEveryone", "-b", "dc=planetexpress,dc=com"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vulcan_test_db: