site_name: Vulcan
site_description: Security Technical Implementation Guide (STIG) creation and validation platform
site_author: MITRE Corporation
site_url: https://mitre.github.io/vulcan/

repo_name: mitre/vulcan
repo_url: https://github.com/mitre/vulcan
edit_uri: edit/master/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - toc.follow

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
      enable_parallel_processing: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started:
    - Quick Start: getting-started/quick-start.md
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Environment Variables: getting-started/environment-variables.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Projects & Components: user-guide/projects-components.md
    - Rules & Controls: user-guide/rules-controls.md
    - STIGs & SRGs: user-guide/stigs-srgs.md
    - InSpec Integration: user-guide/inspec-integration.md
    - Collaboration: user-guide/collaboration.md
  - Deployment:
    - Docker: deployment/docker.md
    - Heroku: deployment/heroku.md
    - Kubernetes: deployment/kubernetes.md
    - Authentication Setup:
      - OIDC/OKTA: deployment/auth/oidc-okta.md
      - LDAP: deployment/auth/ldap.md
      - GitHub OAuth: deployment/auth/github.md
  - Development:
    - Architecture: development/architecture.md
    - Development Setup: development/setup.md
    - Testing: development/testing.md
    - Contributing: CONTRIBUTING.md
    - Release Process: development/release-process.md
    - Vue 3 Migration: development/vue3-migration.md
  - API Reference:
    - Overview: api/overview.md
    - Authentication: api/authentication.md
    - Endpoints: api/endpoints.md
  - Security:
    - Security Policy: SECURITY.md
    - Security Controls: security/security-controls.md
    - Data Encryption: security/data-encryption.md
  - Project:
    - About: about.md
    - Changelog: CHANGELOG.md
    - Roadmap: ROADMAP.md
    - Code of Conduct: CODE_OF_CONDUCT.md
    - License: LICENSE.md
    - Notice: NOTICE.md
    - Release Notes:
      - v2.2.1: release-notes/v2.2.1.md
      - v2.2.0: release-notes/v2.2.0.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mitre/vulcan
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/mitre/vulcan
  version:
    provider: mike