# frozen_string_literal: true

require 'rails_helper'

RSpec.describe Rule do
  describe '::MERGEABLE_FIELDS' do
    it 'is frozen so callers cannot mutate it' do
      expect(described_class::MERGEABLE_FIELDS).to be_frozen
    end

    it 'is a non-empty Array<String>' do
      expect(described_class::MERGEABLE_FIELDS).to be_an(Array)
      expect(described_class::MERGEABLE_FIELDS).not_to be_empty
      expect(described_class::MERGEABLE_FIELDS).to all(be_a(String))
    end

    it 'is a subset of (base_rules.column_names - excluded internal/identity/lifecycle columns)' do
      # The contract: every mergeable field must exist as a real column on
      # base_rules and must NOT be one of the excluded categories. If this
      # ever fires, either a typo crept in or the column was renamed.
      excluded = %w[
        id type component_id srg_rule_id review_requestor_id
        security_requirements_guide_id stig_id stig_rule_id
        locked locked_fields deleted_at
        created_at updated_at
        rule_id srg_id
        inspec_control_file
      ]
      valid_mergeable_columns = described_class.column_names - excluded

      expect(described_class::MERGEABLE_FIELDS - valid_mergeable_columns).to be_empty
    end

    it 'has no overlap with DERIVED_COLUMNS (derived columns are excluded by definition)' do
      expect(described_class::MERGEABLE_FIELDS & described_class::DERIVED_COLUMNS).to be_empty
    end
  end

  describe '::DERIVED_COLUMNS' do
    it 'is frozen' do
      expect(described_class::DERIVED_COLUMNS).to be_frozen
    end

    it 'contains inspec_control_file (regenerated by update_inspec_code after_save)' do
      expect(described_class::DERIVED_COLUMNS).to include('inspec_control_file')
    end

    it 'every derived column exists as a real column on base_rules' do
      expect(described_class::DERIVED_COLUMNS - described_class.column_names).to be_empty
    end
  end

  describe '::NESTED_MERGEABLE_ASSOCIATIONS' do
    subject(:nested) { described_class::NESTED_MERGEABLE_ASSOCIATIONS }

    it 'is frozen' do
      expect(nested).to be_frozen
    end

    it 'every association name resolves to a real AR association on Rule' do
      nested.each_key do |assoc_name|
        expect(described_class.reflect_on_association(assoc_name)).not_to be_nil,
                                                                          "Rule does not have association #{assoc_name.inspect}"
      end
    end

    it 'every listed column exists on the target AR model' do
      nested.each do |assoc_name, config|
        target_class = described_class.reflect_on_association(assoc_name).klass
        all_fields = config[:fields_by_section].values.flatten.uniq
        missing = all_fields - target_class.column_names
        expect(missing).to be_empty,
                           "Columns missing on #{target_class.name}: #{missing.inspect}"
      end
    end

    it 'every section is in RuleConstants::LOCKABLE_SECTION_NAMES' do
      nested.each_value do |config|
        section_names = config[:fields_by_section].keys
        invalid = section_names - RuleConstants::LOCKABLE_SECTION_NAMES
        expect(invalid).to be_empty,
                           "Unknown lockable sections referenced: #{invalid.inspect}"
      end
    end

    it 'identity_keys (when present) are columns on the target model' do
      nested.each do |assoc_name, config|
        next if config[:identity_keys].nil?

        target_class = described_class.reflect_on_association(assoc_name).klass
        missing = config[:identity_keys] - target_class.column_names
        expect(missing).to be_empty,
                           "identity_keys missing on #{target_class.name}: #{missing.inspect}"
      end
    end
  end

  describe 'RuleBuilder::DIRECT_COLUMNS coverage' do
    it 'is the union of MERGEABLE + identity + lifecycle + DERIVED — no overlap, no drift' do
      direct = Import::JsonArchive::RuleBuilder::DIRECT_COLUMNS
      expected = described_class::MERGEABLE_FIELDS +
                 %w[rule_id srg_id locked locked_fields deleted_at] +
                 described_class::DERIVED_COLUMNS

      expect(direct).to match_array(expected)
      expect(direct.size).to eq(direct.uniq.size) # no duplicates
    end
  end
end
