# Vulcan Application Settings
# Default configuration values for rails-settings-cached
# These settings can be overridden at runtime via the database

defaults: &defaults
  # UI Configuration
  welcome_text: <%= ENV['VULCAN_WELCOME_TEXT'] || nil %>
  contact_email: <%= ENV['VULCAN_CONTACT_EMAIL'] || 'admin@vulcan.local' %>
  app_url: <%= ENV['VULCAN_APP_URL'] || nil %>

  # SMTP Configuration
  smtp:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_SMTP']) || false %>
    settings:
      address: <%= ENV['VULCAN_SMTP_ADDRESS'] %>
      port: <%= ENV['VULCAN_SMTP_PORT'] %>
      domain: <%= ENV['VULCAN_SMTP_DOMAIN'] %>
      authentication: <%= ENV['VULCAN_SMTP_AUTHENTICATION']&.to_sym %>
      tls: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_SMTP_TLS']) || false %>
      openssl_verify_mode: <%= ENV['VULCAN_SMTP_OPENSSL_VERIFY_MODE'] %>
      enable_starttls_auto: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_SMTP_ENABLE_STARTTLS_AUTO']) || false %>
      user_name: <%= ENV['VULCAN_SMTP_SERVER_USERNAME'] %>
      password: <%= ENV['VULCAN_SMTP_SERVER_PASSWORD'] %>

  # Authentication Configuration
  local_login:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_LOCAL_LOGIN']) != false %>
    email_confirmation: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_EMAIL_CONFIRMATION']) || false %>
    session_timeout: <%= ENV['VULCAN_SESSION_TIMEOUT'] || 60 %>

  user_registration:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_USER_REGISTRATION']) != false %>

  project:
    create_permission_enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_PROJECT_CREATE_PERMISSION_ENABLED']) != false %>

  # LDAP Configuration
  ldap:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_LDAP']) || false %>
    servers:
      main:
        host: <%= ENV['VULCAN_LDAP_HOST'] || 'localhost' %>
        port: <%= ENV['VULCAN_LDAP_PORT'] || 389 %>
        title: <%= ENV['VULCAN_LDAP_TITLE'] || 'LDAP' %>
        uid: <%= ENV['VULCAN_LDAP_ATTRIBUTE'] || 'uid' %>
        encryption: <%= ENV['VULCAN_LDAP_ENCRYPTION'] || 'plain' %>
        bind_dn: <%= ENV['VULCAN_LDAP_BIND_DN'] %>
        password: <%= ENV['VULCAN_LDAP_ADMIN_PASS'] %>
        base: <%= ENV['VULCAN_LDAP_BASE'] %>

  # OIDC Configuration
  oidc:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_OIDC']) || false %>
    discovery: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_OIDC_DISCOVERY']) || true %>
    strategy: :openid_connect
    title: <%= ENV['VULCAN_OIDC_PROVIDER_TITLE'] || 'OIDC Provider' %>
    args:
      name: :oidc
      scope:
        - :openid
        - :email
        - :profile
      uid_field: 'sub'
      response_type: :code
      discovery: true
      issuer: <%= ENV['VULCAN_OIDC_ISSUER_URL'] %>
      client_auth_method: :secret
      client_signing_alg: <%= ENV['VULCAN_OIDC_CLIENT_SIGNING_ALG']&.to_sym || :RS256 %>
      nonce: <%= proc { SecureRandom.hex(32) } %>
      prompt: <%= ENV['VULCAN_OIDC_PROMPT'] || nil %>
      client_options:
        port: <%= ENV['VULCAN_OIDC_PORT'] || 443 %>
        scheme: <%= ENV['VULCAN_OIDC_SCHEME'] || 'https' %>
        host: <%= ENV['VULCAN_OIDC_HOST'] %>
        identifier: <%= ENV['VULCAN_OIDC_CLIENT_ID'] %>
        secret: <%= ENV['VULCAN_OIDC_CLIENT_SECRET'] %>
        redirect_uri: <%= ENV['VULCAN_OIDC_REDIRECT_URI'] %>
        authorization_endpoint: <%= ENV['VULCAN_OIDC_AUTHORIZATION_URL'] %>
        token_endpoint: <%= ENV['VULCAN_OIDC_TOKEN_URL'] %>
        userinfo_endpoint: <%= ENV['VULCAN_OIDC_USERINFO_URL'] %>
        jwks_uri: <%= ENV['VULCAN_OIDC_JWKS_URI'] %>
        post_logout_redirect_uri: '/'

  # Communication Configuration
  slack:
    enabled: <%= ActiveModel::Type::Boolean.new.cast(ENV['VULCAN_ENABLE_SLACK_COMMS']) || false %>
    api_token: <%= ENV['VULCAN_SLACK_API_TOKEN'] %>
    channel_id: <%= ENV['VULCAN_SLACK_CHANNEL_ID'] %>

  # Provider Configuration
  providers: []

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults