# frozen_string_literal: true

# Blueprint-side companion to ImportedAttribution (model concern). Adds
# the two `field` declarations a role needs in the public JSON shape:
#
#   <role>_display_name  — string (resolved User name → imported_name →
#                          imported_email → nil)
#   <role>_imported      — boolean (true when the user_id-equivalent FK
#                          is nil and any imported_* column is populated)
#
# Both delegate to instance methods generated by
# ImportedAttribution.imported_attribution.
#
# Usage on a Blueprinter::Base subclass:
#
#   class ReviewBlueprint < Blueprinter::Base
#     extend ImportedAttributionFields
#     attribution_fields :triager
#     attribution_fields :adjudicator
#     attribution_fields :commenter
#   end
#
# Mixed via `extend` — `attribution_fields` is a class-level macro on the
# blueprint, paired with Blueprinter's `field` class-level DSL.
module ImportedAttributionFields
  def attribution_fields(role)
    display_method  = "#{role}_display_name"
    imported_method = "#{role}_imported?"

    field display_method.to_sym do |review, _options|
      review.public_send(display_method)
    end

    field :"#{role}_imported" do |review, _options|
      review.public_send(imported_method)
    end
  end
end
