# frozen_string_literal: true

require 'inspec/objects'

# Rules, also known as Controls, are the smallest unit of enforceable configuration found in a
# Benchmark XCCDF.
class Rule < BaseRule
  # Full-text search (search_content / search_phrase) lives on BaseRule —
  # every weighted column is a base_rules column and the associated tables
  # key on base_rule_id, so both requirement kinds are searchable through
  # the one scope. Rule inherits it with the STI type condition applied.

  amoeba do
    # Fresh authoring state on every clone — unlocked, unclaimed, no
    # field-level locks. Shared with the non-amoeba copy sites via one
    # BaseRule primitive (see BaseRule#reset_authored_copy_state). A
    # customize lambda (not amoeba's `set`/`nullify` directives, which did
    # not apply here) makes the plain attribute assignments stick.
    customize(->(_original, copy) { copy.reset_authored_copy_state })

    include_association :additional_answers, if: :single_rule_clone?
  end

  include VulcanAuditable

  vulcan_audited except: %i[component_id review_requestor_id inspec_control_file],
                 associated_with: :component
  has_associated_audits

  belongs_to :component, counter_cache: true
  belongs_to :srg_rule
  belongs_to :review_requestor, class_name: 'User', inverse_of: :reviews, optional: true
  # has_many :reviews lives on BaseRule — reviews attach to authored
  # SrgRules through the same rule_id column.
  has_many :additional_answers, dependent: :destroy

  accepts_nested_attributes_for :additional_answers

  has_and_belongs_to_many :satisfied_by,
                          class_name: 'Rule',
                          join_table: :rule_satisfactions,
                          association_foreign_key: :satisfied_by_rule_id

  has_and_belongs_to_many :satisfies,
                          class_name: 'Rule',
                          join_table: :rule_satisfactions,
                          foreign_key: :satisfied_by_rule_id,
                          association_foreign_key: :rule_id

  before_save :apply_audit_comment, :sort_ident
  after_create :seed_inspec_control_body
  after_destroy :update_component_rules_count
  after_save :update_component_rules_count, :update_inspec_code

  # Lock/review-state invariants (cannot_be_locked_and_under_review,
  # locked_fields validation, destroy guard) live on BaseRule — shared
  # lock semantics across Rule and authored SrgRule.
  validates_with RuleSatisfactionValidator
  validate :review_fields_cannot_change_with_other_fields, on: :update

  validates :rule_id, allow_blank: false, presence: true, uniqueness: { scope: :component_id }

  default_scope { where(deleted_at: nil) }

  # Canonical set of authored content columns on a rule. Excludes
  # identity columns (rule_id, srg_id — used as join keys), lifecycle
  # columns (locked, locked_fields, deleted_at), and derived columns
  # (see DERIVED_COLUMNS).
  #
  # RuleBuilder::DIRECT_COLUMNS derives from this list, as does the
  # backup/restore round-trip field set — keeping one canonical set on
  # the model avoids the silent drift that came from parallel lists.
  MERGEABLE_FIELDS = %w[
    status status_justification artifact_description vendor_comments
    title fixtext fixtext_fixref fix_id
    rule_severity rule_weight version
    ident ident_system changes_requested
    inspec_control_body inspec_control_body_lang inspec_control_file_lang
    legacy_ids vuln_id
  ].freeze

  # Columns regenerated by callbacks from other state (see
  # update_inspec_code on inspec_control_file). Imported from archives
  # for fidelity but excluded from the authored-content set above.
  DERIVED_COLUMNS = %w[inspec_control_file].freeze

  INSPEC_STUB_BODY = <<~RUBY
    # describe file('/tmp') do
    #   it { should be_directory }
    # end
  RUBY

  @single_rule_clone = false

  # A STIG requirement DERIVES from a source SRG requirement, so its SRG
  # identifier is that source's published version — NOT this rule's own
  # version, which is the STIG-side identifier and is free to differ.
  def srg_identifier
    srg_rule&.version
  end

  # If rule clone not coming from a "copy component" action, allow "answers" to be also cloned
  def update_single_rule_clone(rule_clone)
    @single_rule_clone = rule_clone
  end

  def self.from_mapping(rule_mapping, component_id, idx, srg_rules)
    rule = super(self, rule_mapping)
    rule.audits.build(Audited.audit_class.create_initial_rule_audit_from_mapping(component_id))
    rule.component_id = component_id
    rule.srg_rule_id = srg_rules[rule.rule_id]
    # This is what is appended to the component prefix in the UI
    rule.rule_id = idx&.to_s&.rjust(6, '0')

    rule
  end

  # DISA ADNM nesting automation (V4R3 §4.1.9/§4.1.15).
  # Called by RuleSatisfactionsController AND rake tasks.
  def apply_nesting_status!(parent)
    parent_label = "#{parent.component.prefix}-#{parent.rule_id}"
    parent_title = parent.title.presence || parent.srg_rule&.title || parent_label

    update!(
      status: RuleConstants::STATUS_APPLICABLE_DNM,
      status_justification: "This requirement is addressed by #{parent_label} (#{parent_title}).",
      audit_comment: "Auto-set ADNM: satisfied by #{parent_label} (was: #{status})"
    )

    drd = disa_rule_descriptions.first_or_create!
    drd.update!(
      mitigations: "This requirement is fully mitigated by #{parent_label}. " \
                   'With the implementation of this mitigation, the overall risk is fully mitigated.'
    )
  end

  def revert_nesting_status!
    original = find_pre_nesting_status

    update!(
      status: original,
      status_justification: nil,
      audit_comment: "Reverted to #{original}: satisfaction removed"
    )

    disa_rule_descriptions.first&.update!(mitigations: nil)
  end

  ##
  # Serialization is handled by RuleBlueprint.
  # See app/blueprints/rule_blueprint.rb for :navigator, :viewer, :editor views.
  #
  # History revert lives on BaseRule — one kind-agnostic path shared with
  # authored SRG requirements.

  # Returns export data as a hash keyed by DISA header name, so csv_attributes
  # and ExportableRule build rows in header order without fragile positional
  # indices.
  def csv_attributes_hash
    {
      'IA Control' => nist_control_family,
      'CCI' => ident,
      'SRGID' => version,
      'STIGID' => "#{component.prefix}-#{rule_id}",
      'SRG Requirement' => srg_rule.title,
      'Requirement' => title,
      'SRG VulDiscussion' => srg_rule.disa_rule_descriptions.first&.vuln_discussion,
      'VulDiscussion' => disa_rule_descriptions.first&.vuln_discussion,
      'Status' => status,
      'SRG Check' => srg_rule.checks.first&.content,
      'Check' => export_checktext,
      'SRG Fix' => srg_rule.fixtext,
      'Fix' => export_fixtext,
      'Severity' => SEVERITIES_MAP[rule_severity] || rule_severity,
      'Mitigation' => disa_rule_descriptions.first&.mitigations,
      'Artifact Description' => artifact_description,
      'Status Justification' => status_justification,
      'Vendor Comments' => vendor_comments,
      'Satisfies' => satisfaction_text(format: :stig, direction: :satisfies)
    }
  end

  # Array form for backward compatibility — ordered by DISA_EXPORT_HEADERS
  def csv_attributes
    csv_attributes_hash.values_at(*ExportConstants::DISA_EXPORT_HEADERS)
  end

  # Runs inside the parent save's transaction (after_save, not after_commit).
  # update_column participates in the transaction — rolls back if the
  # transaction fails. Does NOT update updated_at — inspec_control_file
  # is a derived column and regeneration should not trigger cache
  # invalidation or misleading audit signals. Errors from Inspec::Object
  # propagate as StatementInvalid and roll back the parent save — this is
  # correct (a rule save that fails InSpec generation should not persist).
  def update_inspec_code
    desc = disa_rule_descriptions.first
    control = Inspec::Object::Control.new
    control.add_header('# -*- encoding : utf-8 -*-')
    control.id = "#{component[:prefix]}-#{rule_id}"
    control.title = title
    control.descriptions[:default] = desc[:vuln_discussion] if desc.present?
    control.descriptions[:rationale] = ''
    control.descriptions[:check] = checks.first&.content
    control.descriptions[:fix] = fixtext
    control.impact = RuleConstants::IMPACTS_MAP[rule_severity]
    control.add_tag(Inspec::Object::Tag.new('severity', rule_severity))
    control.add_tag(Inspec::Object::Tag.new('gtitle', version))
    control.add_tag(Inspec::Object::Tag.new('satisfies', satisfies.includes(:srg_rule).filter_map(&:srg_identifier).uniq.sort)) if satisfies.present?
    control.add_tag(Inspec::Object::Tag.new('gid', PublishedIdentifiers.group(component[:prefix], rule_id)))
    control.add_tag(Inspec::Object::Tag.new('rid', PublishedIdentifiers.rule(component[:prefix], rule_id)))
    control.add_tag(Inspec::Object::Tag.new('stig_id', "#{component[:prefix]}-#{rule_id}"))
    control.add_tag(Inspec::Object::Tag.new('cci', format_inspec_control_cci.uniq.sort)) if ident.present?
    control.add_tag(Inspec::Object::Tag.new('nist', format_inspec_control_nist.uniq.sort))
    if desc.present?
      %i[false_negatives false_positives documentable mitigations severity_override_guidance potential_impacts
         third_party_tools mitigation_control responsibility ia_controls].each do |field|
        control.add_tag(Inspec::Object::Tag.new(field.to_s, desc[field])) if desc[field].present?
      end
    end
    control.add_post_body(inspec_control_body) if inspec_control_body.present?
    # rubocop:disable Rails/SkipsModelValidations -- derived column, bypass callbacks to avoid recursion
    update_column(:inspec_control_file, control.to_ruby)
    # rubocop:enable Rails/SkipsModelValidations
  end

  def basic_fields
    {
      rule_id: rule_id,
      title: title,
      vuln_discussion: disa_rule_descriptions.first&.vuln_discussion,
      check: export_checktext,
      fix: export_fixtext
    }
  end

  # DRY satisfaction text generation — ONE method for all consumers.
  # format: :srg (full SRG IDs for XCCDF/InSpec) or :stig (prefix-rule_id for CSV)
  # direction: :satisfies or :satisfied_by
  # Strip satisfaction keywords and their data, preserving the user's original text.
  # Does NOT consume preceding punctuation — the user's sentence ending stays intact.
  SATISFACTION_STRIP_PATTERN = /\s*\b(Satisfi(?:ed\s+By|es))\s*:.*$/im

  def satisfaction_text(format: :srg, direction: :satisfies)
    relations = direction == :satisfies ? satisfies : satisfied_by
    return nil if relations.blank?

    label = direction == :satisfies ? 'Satisfies' : 'Satisfied By'
    ids = case format
          when :srg
            relations.filter_map(&:srg_identifier)
          when :stig
            relations.map { |r| "#{component.prefix}-#{r.rule_id}" }
          else
            raise ArgumentError, "Unknown satisfaction format: #{format}"
          end

    "#{label}: #{ids.uniq.sort.join(', ')}"
  end

  # Clean vendor comments for export — strips stale satisfaction text,
  # appends fresh generated text from the rule_satisfactions table.
  def export_vendor_comments
    parts = []
    clean = vendor_comments&.sub(SATISFACTION_STRIP_PATTERN, '')&.strip
    parts << clean if clean.present?
    parts << satisfaction_text(format: :stig, direction: :satisfied_by)
    parts << satisfaction_text(format: :stig, direction: :satisfies)
    parts.compact.join('. ')
  end

  # Is the entire row editable? False if inherited or whole-locked.
  def row_editable?
    return false if satisfied_by.any?
    return false if locked?

    true
  end

  # Is a specific field editable on this rule?
  # Checks: inherited → whole lock → section lock.
  def field_editable?(field_key)
    field_sym = field_key.to_sym
    section = RuleConstants::FIELD_TO_SECTION[field_sym]
    raise ArgumentError, "Unknown field for editability check: #{field_key}" unless section

    return false unless row_editable?
    return false if (locked_fields || {}).key?(section)

    true
  end

  private

  def find_pre_nesting_status
    nesting_audit = audits
                    .where("comment LIKE 'Auto-set ADNM:%'")
                    .order(created_at: :desc)
                    .first

    if nesting_audit&.comment&.match(/\(was: (.+)\)/)
      Regexp.last_match(1)
    else
      RuleConstants::STATUS_NYD
    end
  end

  def sort_ident
    self.ident = ident.to_s.split(/, */).uniq.sort.join(', ')
  end

  def format_inspec_control_cci
    rule_cci = ident.split(/, */)
    satisfies_cci = satisfies.pluck(:ident).map { |cci| cci.split(/, */) }.flatten
    rule_cci + satisfies_cci
  end

  def format_inspec_control_nist
    rule_nist = nist_control_family.split(/, */)
    statisfies_nist = satisfies.map(&:nist_control_family).map { |nist| nist.split(/, */) }.flatten
    rule_nist + statisfies_nist
  end

  def single_rule_clone?
    @single_rule_clone
  end

  def export_fixtext
    return nil if status == RuleConstants::STATUS_APPLICABLE_DNM && satisfied_by.any?

    satisfied_by.size.positive? ? satisfied_by.order(:id).first.fixtext : fixtext
  end

  def export_checktext
    return nil if status == RuleConstants::STATUS_APPLICABLE_DNM && satisfied_by.any?

    satisfied_by.size.positive? ? satisfied_by.order(:id).first.checks.first&.content : checks.first&.content
  end

  ##
  # Check to ensure that "review fields" are not changed
  # in the same `.save` action as any "non-review fields"
  def review_fields_cannot_change_with_other_fields
    review_fields = Set.new(%w[review_requestor_id locked changes_requested])
    ignored_fields = %w[updated_at created_at]
    changed_filtered = changed.reject { |f| ignored_fields.include? f }
    any_review_fields_changed = changed_filtered.any? { |field| review_fields.include? field }
    any_non_review_fields_changed = changed_filtered.any? { |field| review_fields.exclude? field }
    # Break early if review and non-review fields have not changed together
    return unless any_review_fields_changed && any_non_review_fields_changed

    errors.add(:base, 'Cannot update review-related attributes with other non-review-related attributes')
  end

  def seed_inspec_control_body
    return if inspec_control_body.present?

    # rubocop:disable Rails/SkipsModelValidations -- avoid retriggering callbacks on create
    update_column(:inspec_control_body, INSPEC_STUB_BODY)
    # rubocop:enable Rails/SkipsModelValidations
  end

  ##
  # This before_save callback method exists because if there are no changes on a record, but a audit_comment
  # is provided, then an Audited::Audit record will be created with no audited_changes. This makes histories
  # unnecessarily confusing.
  #
  # This method addresses that issue by checking the record and its dependent records to see if they are
  # new records, changed, or marked for deletion. If any of those criteria are true, then the audited_comment
  # will be applied ONLY to the correct places.
  #
  def apply_audit_comment
    comment = audit_comment
    return if comment.nil?

    self.audit_comment = nil unless new_record? || changed?

    (rule_descriptions + disa_rule_descriptions + checks + additional_answers).each do |record|
      record.audit_comment = comment if record.new_record? || record.changed? || record._destroy
    end
  end

  def update_component_rules_count
    # don't update component rules count for copy or duplicate component actions
    return unless @single_rule_clone

    component.rules_count = component.rules.where(deleted_at: nil).size
    component.save
  end
end
