# frozen_string_literal: true

require 'zip'

module Export
  module Formatters
    # Generates InSpec profile archives (zip) from components and their rules.
    # Component-based and batch-capable — multi-component exports produce
    # a single zip with subdirectories.
    #
    # Each component becomes:
    #   [dir/]inspec.yml         — profile metadata
    #   [dir/]controls/PREFIX-RULE_ID.rb — one file per AC rule (uses rule.inspec_control_file)
    #
    # Moved from ExportHelper#inspec_helper.
    class InspecFormatter < BaseFormatter
      def component_based?
        true
      end

      def batch_generate?
        true
      end

      # Single component: produces zip with inspec.yml + controls/ at root.
      def generate_from_component(component:, rules:)
        Zip::OutputStream.write_buffer do |zio|
          write_component(zio, component, rules, '')
        end.string
      end

      # Multiple components: produces zip with subdirectories per component.
      def generate_batch(component_rule_pairs:)
        Zip::OutputStream.write_buffer do |zio|
          component_rule_pairs.each do |pair|
            component = pair[:component]
            rules = pair[:rules]
            dir = inspec_dir_name(component)
            write_component(zio, component, rules, dir)
          end
        end.string
      end

      def content_type
        'application/zip'
      end

      def file_extension
        '-stig-baseline.zip'
      end

      private

      def write_component(zio, component, rules, dir)
        # inspec.yml — follows MITRE SAF baseline profile conventions
        zio.put_next_entry("#{dir}inspec.yml")
        zio.write YAML.dump(build_inspec_yml(component))

        # controls/*.rb — one file per rule
        rules.each do |rule|
          zio.put_next_entry("#{dir}controls/#{component[:prefix]}-#{rule[:rule_id]}.rb")
          if rule[:status] == 'Not Yet Determined'
            zio.write nyd_stub_control(component, rule)
          else
            zio.write rule.inspec_control_file
          end
        end
      end

      def nyd_stub_control(component, rule)
        <<~RUBY
          # TODO: Status is 'Not Yet Determined' — this control requires review.
          control '#{component[:prefix]}-#{rule[:rule_id]}' do
            impact 0.0
            title '#{rule[:title].to_s.gsub("'", "\\\\'")}'
            desc 'Not Yet Determined — stub control generated by Vulcan.'
            tag status: 'Not Yet Determined'
          end
        RUBY
      end

      # Build spec-compliant inspec.yml metadata hash with string keys.
      # Follows the pattern used by MITRE SAF STIG baselines:
      # https://github.com/mitre/redhat-enterprise-linux-9-stig-baseline
      # Uses string keys so YAML.dump produces standard `key: value` format
      # instead of Ruby symbol format (`:key: value`).
      def build_inspec_yml(component)
        yml = {
          'name' => component[:name].to_s.parameterize,
          'title' => component[:title].presence || component[:name],
          'maintainer' => component[:admin_name].presence || 'The Authors',
          'copyright' => component[:admin_name].presence || 'The Authors',
          'license' => 'Apache-2.0',
          'summary' => component[:description].presence || "InSpec profile for #{component[:title] || component[:name]}",
          'version' => "#{component[:version] || 0}.#{component[:release] || 0}.0",
          'inspec_version' => '>= 6.0'
        }
        yml['copyright_email'] = component[:admin_email] if component[:admin_email].present?
        yml
      end

      def inspec_dir_name(component)
        version = component[:version] ? "V#{component[:version]}" : ''
        release = component[:release] ? "R#{component[:release]}" : ''
        "#{component[:name].tr(' ', '-')}-#{version}#{release}-stig-baseline/"
      end
    end
  end
end
