name: Update or Create Release Notes

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  update_release_notes:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Vulcan Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install required packages
        run: npm install moment

      - name: Append PR details to the release notes
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          DATE=$(node -e "console.log(require('moment')().format('YYYY-MM-DD'))")

          RELEASE_NOTES_FILE="RELEASE_NOTES.md"

          echo -e "## [PR-${PR_NUMBER}] ${PR_TITLE} (${DATE})\n\n${PR_DESCRIPTION}\n\n### Merged by: ${PR_AUTHOR}\n\n---\n" >> ${RELEASE_NOTES_FILE}

      - name: Commit and push the changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add RELEASE_NOTES.md
          git commit -m "Update RELEASE_NOTES.md with PR-${{ github.event.pull_request.number }} details"
          git push
